### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by StackMobile** [velopert/whotalk.us#1]
#Hello, Velopert
I appreciate so much for your doc - https://velopert.com/.
I am a newbie and want to learn React.js (have some experience in Node.js)
By the way, I want to build your Whotalk,us project in locally (Win 10), I could not do it .

From frontend console, it has some warnings from built current repo . 
And my web page is blank now. 
Could you please give me more detailed instructions to build yours?

In additionally, what do they means by 
SECRET_KEY="SECRET_KEY"
FACEBOOK_SECRET="FACEBOOK_SECRET"
GOOGLE_SECRET="GOOGLE_SECRET"
from env file?

Thanks and looking forward to hearing from you soon.

StackMobile

![image](https://cloud.githubusercontent.com/assets/5441188/22588657/bf2591e8-ea41-11e6-92e2-ffd98a071335.png)
@velopert

**Comment by velopert** [comment]
Hey there, I'm sorry for late reply.

It seems like other people are having the same issue. I will fix it as soon as possible :)


SECRET_KEY="SECRET_KEY"
FACEBOOK_SECRET="FACEBOOK_SECRET"
GOOGLE_SECRET="GOOGLE_SECRET"

SECRET_KEY is used for express-session

> This is the secret used to sign the session ID cookie. This can be either a string for a single secret, or an array of multiple secrets. If an array of secrets is provided, only the first element will be used to sign the session ID cookie, while all the elements will be considered when verifying the signature in requests. ([Link](https://github.com/expressjs/session))

FACEBOOK_SECRET and GOOGLE_SECRET are secret keys for the OAuth

**Comment by StackMobile** [comment]
Thank you for your reply.
Looking forward to hearing your quick fix.

Best.

StackMobile

________________________________

**Comment by velopert** [comment]
I am sorry for late fix. 

It turned out that react-router v4 alpha was making this issue. You have to install again manually by following command:

```
npm install --save react-router@4.0.0.alpha.5
```

It seems like "Match" component got replaced to Route component when react-router was upgraded to beta version.

I fixed this issue temporarily by installing the older version. I will fix this again later on.

Thanks!

**Comment by StackMobile** [comment]
Ok, thanks for your effort.


I will check it out soon and will let you know.


Best regards.


StackMobile


________________________________

**Comment by StackMobile** [comment]
Dear, Velopert

I tried to build it again, but got the same issue.

I am not sure because of  I tried on localhost not real server.

can it be not built on localhost?


If you send me  new source that is built on your end, I  very appreciate that.


Thank you so much.


StackMobile.


________________________________

**Comment by happyname0617** [comment]
I had a same issue and solved by replacing the "react-router" to "react-router-dom" as well as "Match" to "Route"
